# Generated by Django 6.0.2 on 2026-02-23 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_module', '0002_alumni'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemMetadata',
        ),
    ]
