# Generated by Django 6.0.2 on 2026-02-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0002_alter_systemmetadata_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmetadata',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
