# Generated by Django 6.0.2 on 2026-02-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0003_systemmetadata_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemmetadata',
            name='verified_by_admin',
        ),
    ]
