# Generated by Django 6.0 on 2025-12-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.AddField(
            model_name='teacher',
            name='username',
            field=models.CharField(default='temp_teacher', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
