# Generated by Django 6.0.2 on 2026-02-12 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdetails',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contactdetails',
            name='city',
        ),
        migrations.RemoveField(
            model_name='contactdetails',
            name='country',
        ),
        migrations.RemoveField(
            model_name='contactdetails',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='contactdetails',
            name='state',
        ),
        migrations.AddField(
            model_name='academicdetails',
            name='achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='professionaldetails',
            name='career_highlights',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='academicdetails',
            name='college_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='academicdetails',
            name='degree',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='academicdetails',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='academicdetails',
            name='student_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='academicdetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='academicdetails',
            name='year_of_admission',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicdetails',
            name='year_of_graduation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='professionaldetails',
            name='company_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='professionaldetails',
            name='current_company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='professionaldetails',
            name='current_designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='professionaldetails',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='professionaldetails',
            name='linkedin_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='professionaldetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='professionaldetails',
            name='year_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
