# Generated by Django 6.0.2 on 2026-02-26 09:03

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connection',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('follower', 'following')},
        ),
    ]
