# Generated by Django 6.0.2 on 2026-02-26 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_module', '0002_connection_created_at_connection_is_read_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='connection',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='is_read',
        ),
    ]
