# Generated by Django 6.0.2 on 2026-02-14 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_module', '0002_remove_contactdetails_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniengagement',
            name='donation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='alumniengagement',
            name='events_attended',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumniengagement',
            name='membership_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='alumniengagement',
            name='newsletter_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alumniengagement',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
