# Generated by Django 6.0.2 on 2026-02-22 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_module', '0005_connection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicdetails',
            name='college_name',
        ),
    ]
