# Generated by Django 6.0.2 on 2026-02-25 06:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_module', '0006_remove_academicdetails_college_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('follower', 'following')},
        ),
    ]
