# Generated by Django 6.0.2 on 2026-02-25 08:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_module', '0007_alter_connection_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connection',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
