# Generated by Django 6.0.2 on 2026-03-02 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_module', '0007_conversation_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
