# Generated by Django 6.0.2 on 2026-02-26 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_module', '0009_jobevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobEvent',
        ),
    ]
